[chg] Add progress indicator for upload

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -104,14 +104,6 @@ stages:
   [ $(cat /tmp/bc-result) = "1" ] || ( echo 'Required time >= 30 s' >&2; exit 1 )
 
   echo "---------------------------------------"
-  echo "Run messagebus websocket load test"
-  echo "---------------------------------------"
-  poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
-    echo "messagebus-clients.py failed"
-    exit 1
-  )
-
-  echo "---------------------------------------"
   echo "Run file-download memory test"
   echo "---------------------------------------"
   poetry run python ./perftest/file-download.py --clients=5 --file-size=500 --min-download-time=20 --memory-usage-limit 20 || (
@@ -120,6 +112,14 @@ stages:
   )
   poetry run python ./perftest/file-download.py --clients=10 --file-size=200 --min-download-time=20 --memory-usage-limit 20 --range-requests || (
     echo "file-download.py failed (range-requests)"
+    exit 1
+  )
+
+  echo "---------------------------------------"
+  echo "Run messagebus websocket load test"
+  echo "---------------------------------------"
+  poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
+    echo "messagebus-clients.py failed"
     exit 1
   )
 
