cleanup ci/cd

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,6 +5,12 @@ stages:
   - build
   - package
 
+.install_tools: &install_tools |
+  apt update
+  apt -y install debhelper osc
+  pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
+  pip3 install poetry
+
 test:perftest:
   when: manual
   image: ubuntu:focal
@@ -18,65 +24,61 @@ test:perftest:
     MYSQL_USER: "opsi"
     MYSQL_PASSWORD: "opsi"
   stage: test
-  script:
+  script: |
     # Install debian packages
-    - export DEBIAN_FRONTEND=noninteractive
-    - apt update
-    - apt -y install wget git python3-pip python3-venv libmysqlclient-dev mysql-client iproute2 net-tools iputils-ping
+    export DEBIAN_FRONTEND=noninteractive
+    apt update
+    apt -y install wget git python3-pip python3-venv libmysqlclient-dev mysql-client iproute2 net-tools iputils-ping
     # Need redis-timeseries 1.2.8 which is not yet available, installing patched version from obs
-    - wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-server_6.0.4-1_amd64.deb
-    - wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-tools_6.0.4-1_amd64.deb
-    - wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-timeseries_1.2.6-1_amd64.deb
-    - wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/liblzf1_3.6-2_amd64.deb
-    - dpkg -i *.deb || apt -y -f install
+    wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-server_6.0.4-1_amd64.deb
+    wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-tools_6.0.4-1_amd64.deb
+    wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/redis-timeseries_1.2.6-1_amd64.deb
+    wget http://obs.uib.gmbh:82/home:/uibmz:/opsi:/4.2:/experimental/xUbuntu_20.04/amd64/liblzf1_3.6-2_amd64.deb
+    dpkg -i *.deb || apt -y -f install
     # Deactivate mysql strict mode
-    - mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
-    #- mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "CREATE USER 'opsi'@'%' IDENTIFIED BY 'opsi';"
-    - mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON *.* TO 'opsi'@'%';"
+    mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
+    #mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "CREATE USER 'opsi'@'%' IDENTIFIED BY 'opsi';"
+    mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON *.* TO 'opsi'@'%';"
     # Get config files from opsi-server package
-    - "[ -e /etc/opsi ] && rm -r /etc/opsi"
-    - "[ -e ../opsi-server ] && rm -r ../opsi-server"
-    - url=$(git remote -v | grep fetch | cut -f2 | sed s'#/opsiconfd.git.*#/opsi-server.git#')
-    #- branch=$(git rev-parse --abbrev-ref HEAD)
-    - branch=master
-    - GIT_TERMINAL_PROMPT=0 git clone --branch $branch $url ../opsi-server
-    - cp -a ../opsi-server/opsi-server_data/etc /etc/opsi
+    [ -e /etc/opsi ] && rm -r /etc/opsi
+    [ -e ../opsi-server ] && rm -r ../opsi-server
+    url=$(git remote -v | grep fetch | cut -f2 | sed s'#/opsiconfd.git.*#/opsi-server.git#')
+    #branch=$(git rev-parse --abbrev-ref HEAD)
+    branch=master
+    GIT_TERMINAL_PROMPT=0 git clone --branch $branch $url ../opsi-server
+    cp -a ../opsi-server/opsi-server_data/etc /etc/opsi
     # Set mysql address in config
-    - "sed -i 's/127.0.0.1/mysql/' /etc/opsi/backends/mysql.conf"
+    sed -i "s/127.0.0.1/mysql/" /etc/opsi/backends/mysql.conf
     # Use mysql backend only
-    - "echo '.* : mysql' > /etc/opsi/backendManager/dispatch.conf"
+    echo ".* : mysql" > /etc/opsi/backendManager/dispatch.conf
     # Configure opsiconfd
-    - mkdir -p /var/lib/opsi/repository /var/lib/opsi/depot
-    #- "echo redis-internal-url = redis://redis > /etc/opsi/opsiconfd.conf"
-    - "echo log-level-stderr = 4 >> /etc/opsi/opsiconfd.conf"
-    - "echo log-level-file = 0 >> /etc/opsi/opsiconfd.conf"
+    mkdir -p /var/lib/opsi/repository /var/lib/opsi/depot
+    #echo "redis-internal-url = redis://redis" > /etc/opsi/opsiconfd.conf
+    echo "log-level-stderr = 4" >> /etc/opsi/opsiconfd.conf
+    echo "log-level-file = 0" >> /etc/opsi/opsiconfd.conf
     # Installing opsi test modules file
-    - echo "${OPSI_TEST_MODULES}" > /etc/opsi/modules
+    echo "${OPSI_TEST_MODULES}" > /etc/opsi/modules
     # TODO: restore some backend
     # Install poetry
-    - pip3 install poetry
-    - poetry install
-    - poetry run opsiconfd --setup --log-level-stderr=5
+    pip3 install poetry
+    poetry install
+    poetry run opsiconfd --setup --log-level-stderr=5
     # Create adminuser used with opsiconfd-perftest.py
-    - useradd adminuser
-    - echo "adminuser:adminuser" | chpasswd
-    - adduser adminuser opsiadmin  
-    - redis-server /etc/redis/redis.conf &
-    - sleep 5
-    - poetry run opsiconfd &
-    - sleep 5
-    - poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_jsonrpc_authenticated.json -w /tmp/perftest-result
-    - "[ $(grep errors= /tmp/perftest-result | cut -d '=' -f2) -gt 0 ] && ( echo 'Errors in perftest' >&2 && exit 1 )"
-    - "[ $(grep avg_requests_per_second= /tmp/perftest-result | cut -d '=' -f2 | cut -d'.' -f 1) -ge 200 ] || ( echo 'Requests per second < 200' >&2 && exit 1 )"
-    
+    useradd adminuser
+    echo "adminuser:adminuser" | chpasswd
+    adduser adminuser opsiadmin  
+    redis-server /etc/redis/redis.conf &
+    sleep 5
+    poetry run opsiconfd &
+    sleep 5
+    poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_jsonrpc_authenticated.json -w /tmp/perftest-result
+    [ $(grep errors= /tmp/perftest-result | cut -d '=' -f2) -gt 0 ] && ( echo 'Errors in perftest' >&2 && exit 1 )
+    [ $(grep avg_requests_per_second= /tmp/perftest-result | cut -d '=' -f2 | cut -d'.' -f 1) -ge 200 ] || ( echo 'Requests per second < 200' >&2 && exit 1 )
+
 build:linux-pyinstaller:
   stage: build
   script:
-    - apt update
-    - apt -y upgrade
-    - apt -y install curl gettext
-    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
-    - source $HOME/.poetry/env
+    - *install_tools
     - poetry install
     - poetry run opsi-dev-tool -l info --pyinstaller-poetry-build
     - mv opsiconfd opsiconfd.src
@@ -94,37 +96,13 @@ package:obs_int:
   dependencies:
     - build:linux-pyinstaller
   script:
-    - apt update
-    - apt -y install debhelper osc
-    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
-    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.local home:uibmz:opsi:4.2:experimental
+    - *install_tools
+    - python3 -m opsidevtools -l info --obs-update-package https://obs.uib.gmbh home:uibmz:opsi:4.2:experimental
 
 package:obs_ext:
   stage: package
   dependencies:
     - build:linux-pyinstaller
   script:
-    - apt update
-    - apt -y install debhelper osc
-    - pip3 install --trusted-host pypi.uib.gmbh --index-url http://pypi.uib.gmbh:8080/simple opsi-dev-tools
+    - *install_tools
     - python3 -m opsidevtools -l debug --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.2:experimental
-
-#package:deb:
-#  stage: package
-#  dependencies:
-#    - build:linux-pyinstaller
-#  script:
-#    - apt update
-#    - apt -y upgrade
-#    - apt -y install debhelper
-#    - deps=$((dpkg-checkbuilddeps 2>&1 | sed "s/dpkg-checkbuilddeps\:\serror\:\sUnmet build dependencies\://g" | sed "s/[\(][^)]*[\)] //g") || echo -n "")
-#    - echo $deps
-#    - test -z "$deps" || apt -y install $deps
-#    - dpkg-buildpackage -b
-#    - mkdir deb
-#    - mv ../opsiconfd_*.deb deb/
-#  artifacts:
-#    name: 'opsiconfd-deb'
-#    paths:
-#      - deb/*
-#    expire_in: 2 day
