[chg] Update ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,8 +4,7 @@ variables:
   CI_DEBUG_SERVICES: "false"
 
 stages:
-  - unittest
-  - perftest
+  - test
   - build
   - publish
 
@@ -17,175 +16,20 @@ before_script:
 
 after_script:
   - '[ "$CI_DEBUG_SERVICES" = "true" ] && docker compose -f docker/opsiconfd-dev/docker-compose.yml logs'
-  - docker compose -f docker/opsiconfd-dev/docker-compose.yml kill
-
-.install_tools: &install_tools |
-  export DEBIAN_FRONTEND=noninteractive
-  apt update
-  apt -y install debhelper osc tar wget
-  if [ "$(dpkg --print-architecture)" = "amd64" ]; then
-    wget "$OPSIDEVTOOLS_URL_LINUX_X64" -O opsi-dev-tools.tar.gz
-  else
-    wget "$OPSIDEVTOOLS_URL_LINUX_ARM64" -O opsi-dev-tools.tar.gz
-  fi
-  tar -xvf opsi-dev-tools.tar.gz
-  ./opsi-dev-tool --self-install
-
-.prepare_tests: &prepare_tests |
-  # Install debian packages
-  export DEBIAN_FRONTEND=noninteractive
-
-  wget -q https://apt.grafana.com/gpg.key -O /usr/share/keyrings/grafana.key
-  echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list
-
-  apt update
-  apt -y install mariadb-client bc grafana
-
-  # Grant full database access to opsi user
-  mysql --host=mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e "GRANT ALL ON *.* TO 'opsi'@'%';"
-
-  # Start grafana (will report failure but works)
-  /etc/init.d/grafana-server start || true
-
-  [ -e /etc/opsi ] && rm -r /etc/opsi
-  cp -a opsiconfd_data/etc /etc/opsi
-
-  # Configure opsiconfd
-  echo "redis-internal-url = redis://redis" >> tests/data/default-opsiconfd.conf
-  echo "log-level-stderr = 0" >> tests/data/default-opsiconfd.conf
-  echo "log-level-file = 6" >> tests/data/default-opsiconfd.conf
-  echo "log-file = /var/log/opsiconfd-test.log" >> tests/data/default-opsiconfd.conf
-  cat tests/data/default-opsiconfd.conf
-
-  sed -i s'/.*address.*/    "address": "mysql",/' tests/data/opsi-config/backends/mysql.conf
-
-  # Installing opsi test modules file
-  [ -z "${OPSILICSRV_TOKEN}" ] && (echo "OPSILICSRV_TOKEN not set" 1>&2 ; exit 1)
-  mkdir -p /etc/opsi/licenses
-  wget --header="Authorization: Bearer ${OPSILICSRV_TOKEN}" "https://opsi-license-server.uib.gmbh/api/v1/licenses/test?usage=opsiconfd-gitlab-ci" -O /etc/opsi/licenses/test.opsilic
-
-  # Create dirs
-  mkdir -p /var/lib/opsi/repository
-  mkdir -p /var/lib/opsi/depot
-  mkdir -p /var/lib/opsi/workbench
-  mkdir -p /var/log/opsi/clientconnect
-  mkdir -p /var/lib/opsi/public
-  mkdir -p /tftpboot
-
-  # Install poetry
-  pip3 install poetry
-  poetry lock --no-update
-  poetry install
-
-  # Create adminuser used in tests
-  useradd adminuser
-  echo "adminuser:adminuser" | chpasswd
-  adduser adminuser opsiadmin
-  adduser adminuser opsifileadmins
-
-
-.perftest: &perftest |
-  [ -e /var/log/opsiconfd-perftest.log ] && rm /var/log/opsiconfd-perftest.log
-  touch /var/log/opsiconfd-perftest.log
-  chmod 666 /var/log/opsiconfd-perftest.log
-  poetry run opsiconfd -c tests/data/default-opsiconfd.conf -l6 setup
-  poetry run opsiconfd -c tests/data/default-opsiconfd.conf --workers=1 --log-level-file=5 --log-file=/var/log/opsiconfd-perftest.log --max-session-per-ip=20000 &
-  sleep 10
-  cat /var/log/opsiconfd-perftest.log
-
-  date
-  echo "---------------------------------------"
-  echo "Run opsiconfd-perftest"
-  echo "---------------------------------------"
-  poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_session_loading.json -w /tmp/perftest-result
-  cat /tmp/perftest-result
-  [ $(grep errors= /tmp/perftest-result | cut -d '=' -f2) -gt 0 ] && ( cat /tmp/perftest-result; echo 'Errors in perftest' >&2; exit 1 )
-  # Average request time has to be faster than 10 ms
-  echo "$(grep avg_seconds_per_request= /tmp/perftest-result | cut -d '=' -f2)<0.01" | bc > /tmp/bc-result
-  [ $(cat /tmp/bc-result) = "1" ] || ( echo 'Average seconds per request >= 10 ms' >&2; exit 1 )
-
-  echo "---------------------------------------"
-  echo "Run opsiconfd-backend-perftest"
-  echo "---------------------------------------"
-  poetry run ./perftest/opsiconfd-backend-perftest.py --products 100 --clients 100 --iterations 5 > /tmp/perftest-result || (
-    echo "opsiconfd-backend-perftest.py failed"
-    cat /var/log/opsiconfd-perftest.log
-    exit 1
-  )
-  cat /tmp/perftest-result
-  echo "$(grep real= /tmp/perftest-result | cut -d '=' -f2)<30000" | bc > /tmp/bc-result
-  [ $(cat /tmp/bc-result) = "1" ] || ( echo 'Required time >= 30 s' >&2; exit 1 )
-
-  echo "---------------------------------------"
-  echo "Run file-download memory test"
-  echo "---------------------------------------"
-  poetry run python ./perftest/file-download.py --clients=5 --file-size=500 --min-download-time=20 --memory-usage-limit 20 || (
-    echo "file-download.py failed"
-    cat /var/log/opsiconfd-perftest.log
-    exit 1
-  )
-  poetry run python ./perftest/file-download.py --clients=10 --file-size=200 --min-download-time=20 --memory-usage-limit 20 --range-requests || (
-    echo "file-download.py failed (range-requests)"
-    cat /var/log/opsiconfd-perftest.log
-    exit 1
-  )
-
-  echo "---------------------------------------"
-  echo "Run messagebus websocket load test"
-  echo "---------------------------------------"
-  poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
-    echo "messagebus-clients.py failed"
-    cat /var/log/opsiconfd-perftest.log
-    exit 1
-  )
-
-.pytest: &pytest |
-  [ -e /var/log/opsiconfd-test.log ] && rm /var/log/opsiconfd-test.log
-  touch /var/log/opsiconfd-test.log
-  chmod 666 /var/log/opsiconfd-test.log
-  echo "---------------------------------------"
-  echo "Run tests"
-  echo "---------------------------------------"
-  exit_code=0
-  poetry run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests
-
-.run_linters: &run_linters |
-  echo "---------------------------------------"
-  echo "Run linters"
-  echo "---------------------------------------"
-  poetry run pylint --disable=R,fixme,E0012 opsiconfd tests
-  poetry run ruff opsiconfd tests
-  poetry run mypy opsiconfd tests
-
-test:perftest:
-  stage: perftest
-  tags:
-    - linux-docker-x64-hetzner
-  services:
-    - name: mysql:latest
-      command:
-        - --max_connections=1000
-        - --max_allowed_packet=64M
-        - --default-authentication-plugin=mysql_native_password
-    - name: redislabs/redistimeseries:latest
-      alias: redis
-  variables:
-    MYSQL_ROOT_PASSWORD: "opsi"
-    MYSQL_DATABASE: "opsitest"
-    MYSQL_USER: "opsi"
-    MYSQL_PASSWORD: "opsi"
-  script:
-    - *prepare_tests
-    - *perftest
+  - docker compose -f docker/opsiconfd-dev/docker-compose.yml down -v
 
 test:pylint-pytest:
-  stage: unittest
+  stage: test
   tags:
     - linux-docker-x64-hetzner
   services:
   script:
+    - apt-get update
+    - apt-get install --yes bc
+
     - env | grep "OPSILICSRV_TOKEN=" > docker/opsiconfd-dev/local.env
     - docker compose -f docker/opsiconfd-dev/docker-compose.yml up --detach --wait --wait-timeout 30
+    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry lock --no-update
     - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry install
 
     - echo "Run linters"
@@ -195,6 +39,68 @@ test:pylint-pytest:
 
     - echo "Run pytest"
     - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run pytest -x --tb=short -o junit_family=xunit2 --junitxml=testreport.xml --cov-append --cov opsiconfd --cov-report term --cov-report xml -v tests
+
+    - echo "Run perftests"
+    #- docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run opsiconfd -c tests/data/default-opsiconfd.conf -l6 setup
+    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run opsiconfd -c tests/data/default-opsiconfd.conf --workers=1 --log-level-file=5 --log-file=opsiconfd-perftest.log --max-session-per-ip=20000 &
+    - sleep 10
+
+    - echo "Run opsiconfd-perftest"
+    - docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/opsiconfd-perftest.py -l perftest/tests/test_session_loading.json -w perftest-result
+    - cat perftest-result
+    - |
+      [ $(grep errors= perftest-result | cut -d '=' -f2) -gt 0 ] && (
+        echo "Errors in perftest" >&2
+        exit 1
+      )
+    # Average request time has to be faster than 10 ms
+    - echo "$(grep avg_seconds_per_request= perftest-result | cut -d '=' -f2)<0.01" | bc > bc-result
+    - |
+      [ $(cat bc-result) = "1" ] || (
+        echo "Average seconds per request >= 10 ms" >&2
+        exit 1
+      )
+
+    - echo "Run opsiconfd-backend-perftest"
+    - |
+      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/opsiconfd-backend-perftest.py --products 100 --clients 100 --iterations 5 > perftest-result || (
+        echo "opsiconfd-backend-perftest.py failed" >&2
+        cat perftest-result
+        cat opsiconfd-perftest.log
+        exit 1
+      )
+    - cat perftest-result
+    - echo "$(grep real= perftest-result | cut -d '=' -f2)<30000" | bc > /tmp/bc-result
+    - |
+      [ $(cat /tmp/bc-result) = "1" ] || (
+        echo "Required time >= 30 s" >&2
+        exit 1
+      )
+
+    - echo "Run file-download memory test"
+    - |
+      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run python ./perftest/file-download.py --clients=5 --file-size=500 --min-download-time=20 --memory-usage-limit 20 || (
+        echo "file-download.py failed" >&2
+        cat opsiconfd-perftest.log
+        exit 1
+      )
+    - |
+      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run python ./perftest/file-download.py --clients=10 --file-size=200 --min-download-time=20 --memory-usage-limit 20 --range-requests || (
+        echo "file-download.py failed (range-requests)" >&2
+        cat opsiconfd-perftest.log
+        exit 1
+      )
+
+    - echo "Run messagebus websocket load test"
+    - |
+      docker compose -f docker/opsiconfd-dev/docker-compose.yml exec opsiconfd-dev-43 poetry run ./perftest/messagebus-clients.py --clients 500 --event-interval 30 --start-gap 20 || (
+        echo "messagebus-clients.py failed" >&2
+        cat opsiconfd-perftest.log
+        exit 1
+      )
+
+    - echo "Stop docker containers"
+    - docker compose -f docker/opsiconfd-dev/docker-compose.yml down -v
   coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
   artifacts:
     name: 'opsiconfd_test'
@@ -210,10 +116,11 @@ build:linux-pyinstaller:
   stage: build
   tags:
     - linux-docker-x64-hetzner
+  image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11
   script:
     - TRANSIFEX_MIN_REVIEW_RATE=0.0
     - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
-    - *install_tools
+    - opsi-dev-cli self update
     - poetry lock --no-update
     - poetry install
     - poetry run opsi-dev-cli -l debug pyinstaller build
@@ -231,10 +138,11 @@ build:arm64-pyinstaller:
   stage: build
   tags:
     - arm64
+  image: docker.uib.gmbh/opsi/dev/pybuilder:deb9-py3.11
   script:
     - TRANSIFEX_MIN_REVIEW_RATE=0.0
     - '[ "$CI_COMMIT_TAG" = "" ] || TRANSIFEX_MIN_REVIEW_RATE=1.0'
-    - *install_tools
+    - opsi-dev-cli self update
     - poetry lock --no-update
     - poetry install
     - poetry run opsi-dev-cli -l debug pyinstaller build
@@ -269,8 +177,8 @@ publish:obs_ext:
     - build:arm64-pyinstaller
   script:
     - *install_tools
-    - opsi-dev-tool -l info --obs-update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
-    - opsi-dev-cli -l 5 changelog from-git output
+    - opsi-dev-cli -l info packaging obs update-package https://build.opensuse.org home:uibmz:opsi:4.3:development
+    - opsi-dev-cli -l info changelog from-git output
     - opsi-dev-cli release-service register-package-version opsiconfd SERVER_PACKAGE --changelog-file output/changelog.md
     - opsi-dev-cli release-service push-repository-state opsiconfd SERVER_PACKAGE SERVER_PACKAGE-4.3-development
   only:
