Improving the removal of the service files.

diff --git a/debian/opsiconfd.postinst b/debian/opsiconfd.postinst
--- a/debian/opsiconfd.postinst
+++ b/debian/opsiconfd.postinst
@@ -117,14 +117,15 @@ case "$1" in
 		fi
 
 		SYSTEMDUNITDIR=$(pkg-config systemd --variable=systemdsystemunitdir)
-		if [ ! -z "$SYSTEMDUNITDIR" -a -d "$SYSTEMDUNITDIR" -a -d "/etc/opsi/systemdTemplates/"]; then
+		if [ ! -z "$SYSTEMDUNITDIR" -a -d "$SYSTEMDUNITDIR" -a -d "/etc/opsi/systemdTemplates/" ]; then
 			echo "Copying opsiclientd.service to $SYSTEMDUNITDIR"
-			cp "/etc/opsi/systemdTemplates/opsiclientd.service" "$SYSTEMDUNITDIR"
+			cp "/etc/opsi/systemdTemplates/opsiclientd.service" "$SYSTEMDUNITDIR" || echo "Copying service file failed."
 
-			if [ -x "`which systemctl 2>/dev/null`" ]; then
+			systemctl=`which systemctl 2>/dev/null`
+			if [ ! -z "$systemctl" -a -x "$systemctl" ]; then
 				echo "Reloading unit-files"
-				systemctl daemon-reload || echo "Reloading unit-files failed!"
-				systemctl enable opsiconfd.service && echo "Enabled opsiconfd.service" || echo "Enabling opsiconfd.service failed!"
+				$systemctl daemon-reload || echo "Reloading unit-files failed!"
+				$systemctl enable opsiconfd.service && echo "Enabled opsiconfd.service" || echo "Enabling opsiconfd.service failed!"
 			fi
 		fi
 	;;
diff --git a/debian/opsiconfd.postrm b/debian/opsiconfd.postrm
--- a/debian/opsiconfd.postrm
+++ b/debian/opsiconfd.postrm
@@ -13,17 +13,31 @@ case "$1" in
 	;;
 	remove)
 		update-rc.d -f opsiconfd remove >/dev/null || true
+
+		systemctl=`which systemctl 2>/dev/null`
+		if [ -x "$systemctl" ]; then
+			$systemctl disable opsiconfd.service && echo "Disabled opsiconfd.service" || echo "Disabling opsiconfd.service failed!"
+		fi
 	;;
 	purge)
 		deluser pcpatch shadow 1>/dev/null 2>/dev/null || true
 		deluser opsiconfd shadow 1>/dev/null 2>/dev/null || true
 		[ -z "`getent passwd opsiconfd`" ] || userdel opsiconfd
 		rm -f /etc/opsi/opsiconfd.pem  1>/dev/null 2>/dev/null || true
-		
+
+		SYSTEMDUNITDIR=$(pkg-config systemd --variable=systemdsystemunitdir)
+		if [ ! -z "$SYSTEMDUNITDIR" -a -d "$SYSTEMDUNITDIR" -a -e "$SYSTEMDUNITDIR/opsiconfd.service" ]; then
+			systemctl=`which systemctl 2>/dev/null`
+			if [ ! -z "$systemctl" -a -x "$systemctl" ]; then
+				$systemctl disable opsiconfd.service && echo "Disabled opsiconfd.service" || echo "Disabling opsiconfd.service failed!"
+				$systemctl daemon-reload || echo "Reloading unit-files failed!"
+			fi
+
+			rm -f "$SYSTEMDUNITDIR/opsiclientd.service" || echo "Removing opsiclientd.service failed"
+		fi
+
 		db_purge
-	
 	;;
-	
 	*)
 		echo "postrm called with unknown argument \`$1'" >&2
 		exit 1
