Correct name of service file.
More error resistant installation.

4.0.6.4-11 in experimental

diff --git a/debian/opsiconfd.postinst b/debian/opsiconfd.postinst
--- a/debian/opsiconfd.postinst
+++ b/debian/opsiconfd.postinst
@@ -118,8 +118,8 @@ case "$1" in
 
 		SYSTEMDUNITDIR=$(pkg-config systemd --variable=systemdsystemunitdir)
 		if [ ! -z "$SYSTEMDUNITDIR" -a -d "$SYSTEMDUNITDIR" -a -d "/etc/opsi/systemdTemplates/" ]; then
-			echo "Copying opsiclientd.service to $SYSTEMDUNITDIR"
-			cp "/etc/opsi/systemdTemplates/opsiclientd.service" "$SYSTEMDUNITDIR" || echo "Copying service file failed."
+			echo "Copying opsiconfd.service to $SYSTEMDUNITDIR"
+			cp "/etc/opsi/systemdTemplates/opsiconfd.service" "$SYSTEMDUNITDIR" || echo "Copying service file failed."
 
 			systemctl=`which systemctl 2>/dev/null`
 			if [ ! -z "$systemctl" -a -x "$systemctl" ]; then
diff --git a/debian/opsiconfd.postrm b/debian/opsiconfd.postrm
--- a/debian/opsiconfd.postrm
+++ b/debian/opsiconfd.postrm
@@ -33,7 +33,7 @@ case "$1" in
 				$systemctl daemon-reload || echo "Reloading unit-files failed!"
 			fi
 
-			rm -f "$SYSTEMDUNITDIR/opsiclientd.service" || echo "Removing opsiclientd.service failed"
+			rm -f "$SYSTEMDUNITDIR/opsiconfd.service" || echo "Removing opsiconfd.service failed"
 		fi
 
 		db_purge
