Assume systemctl exists.

diff --git a/debian/opsiconfd.postinst b/debian/opsiconfd.postinst
--- a/debian/opsiconfd.postinst
+++ b/debian/opsiconfd.postinst
@@ -110,10 +110,8 @@ case "$1" in
 		chown opsiconfd:opsiadmin /var/lib/opsiconfd/rrd
 
 		systemctl=`which systemctl`
-		if [ ! -z "$systemctl" -a -x "$systemctl" ]; then
-			$systemctl daemon-reload || echo "Reloading unit-files failed!"
-			$systemctl enable opsiconfd.service && echo "Enabled opsiconfd.service" || echo "Enabling opsiconfd.service failed!"
-		fi
+		$systemctl daemon-reload || echo "Reloading unit-files failed!"
+		$systemctl enable opsiconfd.service && echo "Enabled opsiconfd.service" || echo "Enabling opsiconfd.service failed!"
 	;;
 
 	abort-upgrade|abort-remove|abort-deconfigure)
