changes in postinst for ucs install cd running opsiconfd-guard script with bash not sh

diff --git a/debian/opsiconfd.postinst b/debian/opsiconfd.postinst
--- a/debian/opsiconfd.postinst
+++ b/debian/opsiconfd.postinst
@@ -5,8 +5,6 @@
 case "$1" in
 	configure)
 		
-		FQDN=$(hostname -f)
-		
 		if [ -z "`getent group pcpatch`" ]; then
 			groupadd -g 992 pcpatch
 		fi
@@ -25,10 +23,18 @@ case "$1" in
 		if [ ! -e "/etc/opsi/opsiconfd.pem" ]; then
 			umask 077
 			
-			if [ -e "/etc/univention/ssl/$FQDN/cert.pem" -a -e "/etc/univention/ssl/$FQDN/private.key" ]; then
-				# Using ucs key and cert
-				cat /etc/univention/ssl/$FQDN/private.key > /etc/opsi/opsiconfd.pem
-				grep -A 50 "BEGIN CERTIFICATE" /etc/univention/ssl/$FQDN/cert.pem >> /etc/opsi/opsiconfd.pem
+			if [ -e "/usr/sbin/ucr" ]; then
+				# Running on ucs
+				hn=$(/usr/sbin/ucr get hostname)
+				dn=$(/usr/sbin/ucr get domainname)
+				FQDN="${hn}.${dn}"
+				if [ -e "/etc/univention/ssl/$FQDN/cert.pem" -a -e "/etc/univention/ssl/$FQDN/private.key" ]; then
+					# Using ucs key and cert
+					cat /etc/univention/ssl/$FQDN/private.key > /etc/opsi/opsiconfd.pem
+					grep -A 50 "BEGIN CERTIFICATE" /etc/univention/ssl/$FQDN/cert.pem >> /etc/opsi/opsiconfd.pem
+				else
+					echo "UCS ssl server key/cert not found in /etc/univention/ssl/$FQDN" 1>&2
+				fi
 			else
 				db_get opsiconfd/cert_country
 				cert_country=$RET
